"""add_map_description

Revision ID: 154511419244
Revises: 261fda8ba909
Create Date: 2026-06-30 23:24:15.791376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '154511419244'
down_revision: Union[str, None] = '261fda8ba909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mod_descriptions', sa.Column('map_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mod_descriptions', 'map_description')
    # ### end Alembic commands ###
