"""add_assets_table

Revision ID: 261fda8ba909
Revises: 5440e91e51de
Create Date: 2026-06-28 22:11:28.469204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261fda8ba909'
down_revision: Union[str, None] = '5440e91e51de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('MAP', name='entitytype', native_enum=False, length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.Enum('ICON', 'OVERVIEW', 'PREVIEW', name='assettype', native_enum=False, length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('asset_uri', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_entity', 'assets', ['entity_type', 'entity_id'], unique=False)
    op.drop_column('mod_descriptions', 'icon_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mod_descriptions', sa.Column('icon_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index('ix_assets_entity', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
