"""add mod description, map description, changelogs, assets

Revision ID: 3d845283e345
Revises: 6a136406cbee
Create Date: 2026-07-05 00:49:32.122282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d845283e345'
down_revision: Union[str, None] = '6a136406cbee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('MAP', name='entitytype', native_enum=False, length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.Enum('ICON', 'OVERVIEW', 'PREVIEW', name='assettype', native_enum=False, length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('asset_uri', sa.String(length=500), nullable=False),
    sa.Column('is_ingested', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_entity', 'assets', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_assets_is_ingested'), 'assets', ['is_ingested'], unique=False)
    op.create_table('mod_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mod_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mod_dependencies_mod_id'), 'mod_dependencies', ['mod_id'], unique=True)
    op.create_table('map_changelogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('requires_new_savegame', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_changelogs_map_id'), 'map_changelogs', ['map_id'], unique=False)
    op.create_table('map_dependencies',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('dependency_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['mod_dependencies.id'], ),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('map_id', 'dependency_id')
    )
    op.create_table('mod_descriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('map_description', sa.Text(), nullable=True),
    sa.Column('config_filename', sa.String(length=255), nullable=True),
    sa.Column('vehicles_filename', sa.String(length=255), nullable=True),
    sa.Column('placeables_filename', sa.String(length=255), nullable=True),
    sa.Column('items_filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mod_descriptions_map_id'), 'mod_descriptions', ['map_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mod_descriptions_map_id'), table_name='mod_descriptions')
    op.drop_table('mod_descriptions')
    op.drop_table('map_dependencies')
    op.drop_index(op.f('ix_map_changelogs_map_id'), table_name='map_changelogs')
    op.drop_table('map_changelogs')
    op.drop_index(op.f('ix_mod_dependencies_mod_id'), table_name='mod_dependencies')
    op.drop_table('mod_dependencies')
    op.drop_index(op.f('ix_assets_is_ingested'), table_name='assets')
    op.drop_index('ix_assets_entity', table_name='assets')
    op.drop_table('assets')
