"""create_mod_desc_table_and_dependencies

Revision ID: 5440e91e51de
Revises: 6a136406cbee
Create Date: 2026-06-28 20:04:56.333039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5440e91e51de'
down_revision: Union[str, None] = '6a136406cbee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mod_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mod_dependencies_mod_id'), 'mod_dependencies', ['mod_id'], unique=True)
    op.create_table('map_dependencies',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('dependency_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['mod_dependencies.id'], ),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('map_id', 'dependency_id')
    )
    op.create_table('mod_descriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_filename', sa.String(length=255), nullable=True),
    sa.Column('config_filename', sa.String(length=255), nullable=True),
    sa.Column('vehicles_filename', sa.String(length=255), nullable=True),
    sa.Column('placeables_filename', sa.String(length=255), nullable=True),
    sa.Column('items_filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mod_descriptions_map_id'), 'mod_descriptions', ['map_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mod_descriptions_map_id'), table_name='mod_descriptions')
    op.drop_table('mod_descriptions')
    op.drop_table('map_dependencies')
    op.drop_index(op.f('ix_mod_dependencies_mod_id'), table_name='mod_dependencies')
    op.drop_table('mod_dependencies')
    # ### end Alembic commands ###
