"""add data_uri and zip_filename

Revision ID: 62554e655e86
Revises: 38c412c55796
Create Date: 2025-07-29 12:46:02.063493

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '62554e655e86'
down_revision: Union[str, None] = '38c412c55796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('zip_filename', sa.String(length=100), nullable=True))
    op.add_column('maps', sa.Column('data_uri', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maps', 'data_uri')
    op.drop_column('maps', 'zip_filename')
    # ### end Alembic commands ###
