"""rename_map_desc_to_tagline

Revision ID: 8f0b40e2ee12
Revises: dd2706bcfbf3
Create Date: 2026-08-01 12:16:31.279842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0b40e2ee12'
down_revision: Union[str, None] = 'dd2706bcfbf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mod_descriptions', sa.Column('tagline', sa.Text(), nullable=True))
    op.drop_column('mod_descriptions', 'map_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mod_descriptions', sa.Column('map_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('mod_descriptions', 'tagline')
    # ### end Alembic commands ###
