"""add is_ingested column

Revision ID: 9bcfc1353cab
Revises: 3d845283e345
Create Date: 2026-07-12 21:39:26.055383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bcfc1353cab'
down_revision: Union[str, None] = '3d845283e345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('is_ingested', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_assets_is_ingested'), 'assets', ['is_ingested'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_is_ingested'), table_name='assets')
    op.drop_column('assets', 'is_ingested')
    # ### end Alembic commands ###
