"""add_map_information

Revision ID: dd2706bcfbf3
Revises: 3d845283e345
Create Date: 2026-07-31 23:48:34.660916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2706bcfbf3'
down_revision: Union[str, None] = '3d845283e345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_information',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('map_i3d_filename', sa.String(length=255), nullable=True),
    sa.Column('farmlands_filename', sa.String(length=255), nullable=True),
    sa.Column('fields_filename', sa.String(length=255), nullable=True),
    sa.Column('fill_types_filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_information_map_id'), 'map_information', ['map_id'], unique=True)
    op.drop_index(op.f('ix_assets_entity'), table_name='assets')
    op.create_index('ix_assets_entity', 'assets', ['entity_type', 'entity_id', 'is_ingested'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assets_entity', table_name='assets')
    op.create_index(op.f('ix_assets_entity'), 'assets', ['entity_type', 'entity_id'], unique=False)
    op.drop_index(op.f('ix_map_information_map_id'), table_name='map_information')
    op.drop_table('map_information')
    # ### end Alembic commands ###
