"""add_map_changelogs

Revision ID: e1b6d51f4b94
Revises: 154511419244
Create Date: 2026-07-05 00:14:01.722899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b6d51f4b94'
down_revision: Union[str, None] = '154511419244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_changelogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('requires_new_savegame', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_changelogs_map_id'), 'map_changelogs', ['map_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_map_changelogs_map_id'), table_name='map_changelogs')
    op.drop_table('map_changelogs')
    # ### end Alembic commands ###
