"""add_area_types

Revision ID: f8865ad16e05
Revises: e1b752c145e9
Create Date: 2026-08-09 10:49:54.524164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8865ad16e05'
down_revision: Union[str, None] = 'e1b752c145e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_farmlands', sa.Column('area_types', sa.JSON(none_as_null=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_farmlands', 'area_types')
    # ### end Alembic commands ###
