farmhand:
  parser_filters:
    always_include:
      overview:
        - "textures/ui/*.dds"
        - "preview.dds"
        - "overview.dds"
        - "overview_*.dds"
      xml:
        - "config/*.xml"
        - "xml/*.xml" # Some maps (i.e. Pallegney) store XML in /xml
        - "xmlFiles/*.xml"
      grle_data:
        - "data/*.grle"
      map:
        - "map.i3d"
        - "mapEU.i3d"
        - "mapDE.i3d"
      mod:
        - "modDesc.xml"
        - "icon_*.dds"

    # Specific filenames to exclude even if they match an always_include pattern.
    # Use for files that contain no useful map data (e.g. trafficSystems, Trains, etc.)
    excluded_files:
      - "trafficSystem.xml"
      - "aiSystem.xml"
      - "animatedObjects.xml"
      - "footballField.xml"
      - "handTools.xml"
      - "motionPathEffects.xml"
      - "pedestrianSystem.xml"
      - "colorGradingNight.xml"
      - "colorGrading.xml"
      - "collectibles.xml"

  extra_content:
    # Vehicles & Equipment
    - "vehicles"
    - "equipment"
    - "buy"

    # Placeables & structures
    - "placeables"
    - "customsPlaceables"
    - "sellpoints"

    # Extra crops / goods
    - "pallets"

    # Misc
    - "icons"