name: "Run Pytest"

on:
  pull_request:

env:
  MINIMUM_COVERAGE: 50
  TESTING: True

jobs:
  pytest-coverage:
    name: "Pytest Coverage"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up uv"
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.14"

      - name: "Create database directory"
        run: mkdir -p instance

      - name: "Run Pytest with coverage"
        run: uv run pytest --cov src --cov-fail-under=${{ env.MINIMUM_COVERAGE }} -vv

  pytest-tests:
    name: "Pytest Tests"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up uv"
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.14"

      - name: "Create database directory"
        run: mkdir -p instance

      - name: "Run Pytest"
        run: uv run pytest tests -vv