name: 'Run Ruff lint'

on:
  pull_request:

jobs:
  run_linter:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Set up uv'
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.14"

      - name: 'Run Ruff Lint'
        run: uvx ruff check